### ISSUE TITLE
support different friction coefficients for rail segements

### ISSUE THREAD

**Issue by pollend** [Terasology/Rails#20]
At the moment there is a java file in rails called Constants with a value called FRICTION_COFF. It should be possible to define other rail segments with different amounts of friction.  

Add a friction coefficient value to RailComponent. This also involves tweaking the CartMotionSystem and using the friction coefficient of the current rail segment that the cart is currently on rather then using a fixed coefficient for all segments.

**Comment by eviltak** [comment]
I would suggest that this issue be closed, since it is resolved in #27.
