### ISSUE TITLE
Connecting Carts

### ISSUE THREAD

**Issue by pollend** [Terasology/Rails#21]
The old implementation of Rails let the user connect one cart to another. This was dropped with the rework of rails. The new impulse solver will need to be extended to support connecting two carts together.

The current implementation of the impulse solver is fairly simplistic and for the mod this works really well. This will require tweaking the impulse solver to allow carts to be connected to each other. Collisions between carts should be ignored to prevent unintended jumping. 

There are some basic elements provided but beyond that this requires extending the impulse system. There are some nice resources on the subject but translating those details is not easy.

Old Implementation: https://www.youtube.com/watch?time_continue=22&v=_SwESByZtZg

**Comment by eviltak** [comment]
For anyone interested, this feature is tracked by the `feature-connecting-carts` branch until it is ready to be merged into `develop`.

**Comment by eviltak** [comment]
Now that the branch has been merged into `develop`, I think this issue can be closed.

**Comment by pollend** [comment]
@eviltak thanks
