### ISSUE TITLE
Carts inch along when nothing is pushing them

### ISSUE THREAD

**Issue by eviltak** [Terasology/Rails#24]
After carts are pushed, they will inch along when they should have slowed down to a stop.

This is due to the velocity magnitude _not_ being clamped to zero when the magnitude of friction impulse is greater than the speed.

## Reproduction
Place a cart on a rail and push it. More often than not you will notice that the cart keeps inching forward even after a long time.

**Comment by eviltak** [comment]
@pollend @Cervator I'd like to take this up as a GCI task.

**Comment by jellysnake** [comment]
If you're confident that you can undertake it as a GCI task we can make it one for you.
I'd recommend completing the other tasks you've expressed interest in first though. GCI has a while before it's over :)

**Comment by eviltak** [comment]
@jellysnake I'd appreciate the creation of a GCI task, thanks. Since I have already identified the problem and the solution, I expect the resolution of the task to be pretty quick.

**Comment by jellysnake** [comment]
So I'm happy to make this a gci task along with SegmentedPaths#3 and other issues you've expressed interest in.  
However you should finish the task you are currently working on. Once you've done that, you can either claim a GCI task or you then you can let us know which issue you would like to take on next (and we can make it an issue)
