### ISSUE TITLE
Blowing up rails causes exceptions

### ISSUE THREAD

**Issue by anuar2k** [Terasology/Rails#32]
In 75% times when a rail gets blown up (it doesn't matter what causes the explosion) the NullPointerException is raised. It's really hard to define when it does happen, but it's easy to replicate the issue.

Log:
https://gist.github.com/anuar2k/6d9cc6885ec33d415711e9b16e60d07f

**Comment by eviltak** [comment]
Just as IntelliJ quite nicely points out, dereferencing the `blockDamageModifierComponent` causes a NPE. This is an engine issue.
