### ISSUE TITLE
Rails Test Not Clear (I have updated it)

### ISSUE THREAD

**Issue by SurajDatta** [Terasology/Rails#34]
Hi, I have updated the documentation of Rail Test as the task : Update Test Plan for the Rails Module ( MovingBlocks ) suggested me to. Please find the link of the new gist linked below.
https://gist.github.com/SurajDatta/9b47eabf3335a7c0cd185daed0665583

Hope you like it!

**Comment by pollend** [comment]
are you able to edit the wiki?

https://github.com/Terasology/Rails/wiki/Rails-Test-Plan

**Comment by SurajDatta** [comment]
Hi, @pollend I have updated the wiki :), please have a look: https://github.com/Terasology/Rails/wiki/Rails-Test-Plan

**Comment by Cervator** [comment]
Closing long ago completed issue. Thanks @SurajDatta ! :-)
