### ISSUE TITLE
Make `ModuleTestingEnvironment` and `CoreAssets` dependencies optional

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/Rails#53]
Only references to CoreAssets are in tests.
Health has ModuleTestingEnvironment as optional dependency as it's only required for testing (see https://github.com/Terasology/Health/blob/develop/module.txt#L9).

**Comment by gaurav9822** [comment]
@jdrueckert can I take this one? 

Also, please mark the repo as "hacktoberfest"

**Comment by skaldarnar** [comment]
@gaurav9822 please go ahead 👍 Repository now has the "hacktoberfest" topic 🤓 

Happy Coding!
